import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'routing/router.dart';
import 'theme/theme.dart';

// Note: AppLocalizations will be generated by the flutter l10n package at build time.
// During structural foundation setup, we supply standard delegates so it compiles cleanly
// and falls back gracefully, then binds generated classes once build triggers.
class AmmaNannaApp extends ConsumerWidget {
  const AmmaNannaApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);

    return MaterialApp.router(
      title: 'EasySave',
      theme: AppDesignTheme.lightTheme,
      debugShowCheckedModeBanner: false,
      
      // Enforce GoRouter instance from Riverpod provider
      routerConfig: router,

      // Telugu-First localization bindings (Rule 3 and PRD notes)
      locale: const Locale('te', 'IN'),
      supportedLocales: const [
        Locale('te', 'IN'), // Telugu (India) as template anchor
        Locale('te'),
      ],
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],

      // Ensure text scaling and layouts remain readable (minimum 18sp bounds)
      builder: (context, child) {
        final double textScale = MediaQuery.textScaleFactorOf(context);
        return MediaQuery(
          // Protect against very small systems font settings by mapping to a minimum scale
          data: MediaQuery.of(context).copyWith(
            textScaleFactor: textScale < 1.0 ? 1.0 : textScale,
          ),
          child: child!,
        );
      },
    );
  }
}
